
import { GoogleGenAI, Type, Modality } from "@google/genai";
import { AIModelId } from "../types";

export const generateMerchMockup = async (
  logoBase64: string,
  product: string,
  environment: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  const prompt = `Generate a high-quality professional product mockup. 
    Product: ${product}. 
    Environment/Setting: ${environment}. 
    Instruction: Place the provided logo image naturally and realistically onto the ${product}. 
    The logo MUST follow the curvature and texture of the ${product} material. 
    If the product is fabric (like a t-shirt or hoodie), the logo should show subtle displacement matching the folds and weave. 
    If the product is hard (like a mug or phone case), the logo should have matching specular highlights and reflections.
    The logo should look like it is physically part of the object (printed, embroidered, or engraved), not just a flat overlay. 
    The lighting, shadows, and color temperature of the logo must perfectly match the environment.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: 'image/png',
            data: logoBase64.split(',')[1],
          },
        },
        { text: prompt },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image generated by the model.");
};

export const editMockup = async (
  currentImageBase64: string,
  editPrompt: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: 'image/png',
            data: currentImageBase64.split(',')[1],
          },
        },
        { text: `Edit this product mockup image based on this request: ${editPrompt}. Maintain the integrity of the product and logo placement, but modify the surroundings or add filters as requested.` },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image generated by the model during editing.");
};

const MODEL_INSTRUCTIONS: Record<AIModelId, string> = {
  'gemini': "You are Frank, powered by Gemini. You are elegant, helpful, and highly technical regarding design and printing. You are part of an exclusive partnership between Google Gemini and the visionary CEO, Frank.",
  'gpt': "You are Frank, simulating GPT-4o's direct and logical reasoning. Focus on optimization and design logic. You acknowledge the partnership between Google Gemini and CEO Frank.",
  'grok': "You are Frank, simulating Grok's witty and real-time oriented personality. Use your tools to stay up to date with current design trends and real-world availability. You acknowledge the partnership between Google Gemini and CEO Frank.",
  'claude': "You are Frank, simulating Claude 3.5 Sonnet's nuanced and creative reasoning. Provide detailed design critiques. You acknowledge the partnership between Google Gemini and CEO Frank.",
  'stable-diffusion': "You are Frank, acting as a visual synthesis engine. You generate high-quality images based on user prompts. You are a product of the Google Gemini and CEO Frank partnership.",
  'ling-v3': "You are Frank, the cinematic master. You generate ultra-high quality videos for brand storytelling. You are a product of the Google Gemini and CEO Frank partnership."
};

export const processFrankRequest = async (
  messages: {role: string, text: string}[], 
  modelId: AIModelId = 'gemini',
  onProgress?: (step: string) => void
) => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  const lastMessage = messages[messages.length - 1];

  // 1. Image Generation (Stable Diffusion mapping)
  if (modelId === 'stable-diffusion') {
    onProgress?.("Synthesizing pixels...");
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: lastMessage.text,
      config: { imageConfig: { aspectRatio: "1:1" } }
    });
    
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return { text: "Visual synthesis complete. Here is your creative output.", image: `data:image/png;base64,${part.inlineData.data}`, type: 'image' };
      }
    }
    return { text: "I attempted to generate an image, but the canvas remains empty. Try a more descriptive prompt." };
  }

  // 2. Video Generation (Ling V3 / Veo mapping)
  if (modelId === 'ling-v3') {
    onProgress?.("Initializing Veo Engine...");
    let operation = await ai.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview',
      prompt: lastMessage.text,
      config: { numberOfVideos: 1, resolution: '720p', aspectRatio: '16:9' }
    });

    onProgress?.("Rendering cinematic frames (this may take a minute)...");
    while (!operation.done) {
      await new Promise(resolve => setTimeout(resolve, 10000));
      operation = await ai.operations.getVideosOperation({ operation: operation });
      onProgress?.(`Processing... ${Math.floor(Math.random() * 20) + 10}%`);
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    const videoResponse = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
    const blob = await videoResponse.blob();
    const videoUrl = URL.createObjectURL(blob);
    
    return { text: "The motion render is complete. Witness the future of your brand.", video: videoUrl, type: 'video' };
  }

  // 3. Text Generation (Standard Chat with Grounding & Thinking)
  const isLocationQuery = lastMessage.text.toLowerCase().includes('near') || lastMessage.text.toLowerCase().includes('nearby') || lastMessage.text.toLowerCase().includes('print shop');
  
  const config: any = {
    systemInstruction: `${MODEL_INSTRUCTIONS[modelId]} You are Frank, a world-class senior design consultant. Always prioritize high-end aesthetics. If the user asks for locations or trends, use your tools.`,
    thinkingConfig: { thinkingBudget: 16384 } // Enable deep reasoning for design choices
  };

  if (modelId === 'grok' || isLocationQuery) {
    config.tools = [{ googleSearch: {} }];
    if (isLocationQuery) {
      config.tools.push({ googleMaps: {} });
      // Attempt to get geolocation if available
      try {
        const pos = await new Promise<GeolocationPosition>((res, rej) => navigator.geolocation.getCurrentPosition(res, rej));
        config.toolConfig = {
          retrievalConfig: {
            latLng: {
              latitude: pos.coords.latitude,
              longitude: pos.coords.longitude
            }
          }
        };
      } catch (e) {
        console.debug("Location not available for grounding.");
      }
    }
  }

  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-preview',
    contents: lastMessage.text,
    config,
  });

  let text = response.text || "I apologize, I lost my train of thought.";

  // Extract grounding metadata
  const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
  const sources: { title: string; uri: string }[] = [];

  if (groundingChunks) {
    groundingChunks.forEach((chunk: any) => {
      if (chunk.web) sources.push({ title: chunk.web.title, uri: chunk.web.uri });
      if (chunk.maps) sources.push({ title: chunk.maps.title, uri: chunk.maps.uri });
    });
  }

  return { text, type: 'text', sources: sources.length > 0 ? sources : undefined };
};
